### ISSUE TITLE
Permettre de recommencer une partie pré-remplie

### ISSUE THREAD

**Issue by blue112** [AurelieV/werewolves#1]
Avoir un bouton "recommencer" après avoir cliqué sur terminé.

Selectionner les mêmes cartes sur le premier écran et sur le second pré-remplir les noms.

**Comment by AurelieV** [comment]
@blue112 obligé de repasser par l'écran de sélection des noms? Ou direct assignation des rôles?

**Comment by blue112** [comment]
Je préfère repasser par les deux écrans, comme ça si quelqu'un se rajoute ou part, je peux gérer.
