### ISSUE TITLE
Permettre d'exporter les résultats

### ISSUE THREAD

**Issue by blue112** [AurelieV/werewolves#3]
Avoir un simple champs texte avec le rôle et le nom de chaque joueur, ou un table html que je peux screener pour reporter les scores à la fin.

Nice to have: Me donner un champs texte pour indiquer le "résultat" de la partie.

**Comment by AurelieV** [comment]
@blue112 tu veux pouvoir télécharger un fichier, ou juste une vue pour prendre un screenshot?

**Comment by blue112** [comment]
Un screenshot ça suffit imo.
